BlueSports/BlueSports/Controllers/Components/HeaderCartViewComponent.cs
using BlueSports.HandleAdmin.Extension;
using BlueSports.HandleAdmin.ModelViews;
using Microsoft.AspNetCore.Mvc;

namespace BlueSports.Controllers.Components
{
    public class HeaderCartViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var cart = HttpContext.Session.Get<List<CartItem>>("GioHang");
            return View(cart);
        }
    }
}

BlueSports/BlueSports/Controllers/ProductController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BlueSports.Data;
using BlueSports.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PagedList.Core;
using Microsoft.AspNetCore.Hosting;
using Newtonsoft.Json;

namespace BlueSports.Controllers
{
    public class ProductController : Controller
    {
        // Danh sách sản phẩm mẫu
        private readonly ApplicationDbContext _context;
        private readonly INotyfService _notyfService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        public ProductController(ApplicationDbContext context, INotyfService notyfService, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _notyfService = notyfService;
            _webHostEnvironment = webHostEnvironment;
        }


        [Route("ProductList", Name = "ShopProduct")]
        public IActionResult Index(int? page)
        {
            try
            {
                // Thiết lập phân trang
                int pageNumber = page ?? 1;
                int pageSize = 10;
                ViewBag.Categories = _context.Categories;
                // Lấy danh sách sản phẩm và sắp xếp theo CreatedDate
                var products = _context.Products
                    .Include(p => p.Category)
                    .AsNoTracking()
                    .OrderBy(x => x.DateAdded);

                // Áp dụng phân trang
                IPagedList<Product> models = new PagedList<Product>(products, pageNumber, pageSize);

                // Thiết lập dữ liệu danh mục cho ViewBag
                ViewBag.CurrentPage = pageNumber;
                ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryID", "CategoryName");

                return View(models);
            }
            catch (Exception ex)
            {
                // Ghi log lỗi nếu cần
                Console.WriteLine($"Error: {ex.Message}");
                return RedirectToAction("Index", "Home");
            }
        }




        [Route("/{productName}-{id:int}", Name = "ProductDetails")]
        public IActionResult Details(int id)
        {
            try
            {
                // Lấy sản phẩm và bao gồm thông tin danh mục (Cate)
                var product = _context.Products
                    .Include(x => x.Category) // Điều chỉnh nếu tên bảng là "Category"
                    .FirstOrDefault(x => x.ProductID == id);
                
                
                // Kiểm tra nếu sản phẩm không tồn tại
                if (product == null)
                {
                    return RedirectToAction("Index");
                }

                // Tạo SelectList cho danh mục nếu cần hiển thị danh mục khác
                ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryID", "CategoryName");

                // Trả về View với model product
                return View(product);
            }
            catch (Exception ex)
            {
                // Ghi log lỗi nếu cần
                Console.WriteLine($"Error: {ex.Message}");
                return RedirectToAction("Index", "Home");
            }
        }


        

        public IActionResult Filter(int categoryId = 0)
        {
            string url;

            if (categoryId > 0)
            {
                url = $"/danhmuc/{categoryId}";
            }
            else
            {
                url = "/ProductList";
            }

            return Json(new { status = "success", redirecturl = url });
        }

        [Route("danhmuc/{categoryId}", Name = "ListProduct")]
        public IActionResult List(int categoryId, int page = 1)
        {
            try
            {
                var pageSize = 10;
                var category = _context.Categories.AsNoTracking().SingleOrDefault(x => x.CategoryID == categoryId);

                if (category == null)
                {
                    return RedirectToAction("Index", "Home");
                }

                var lsTinDangs = _context.Products
                    .Include(x => x.Category)
                    .AsNoTracking()
                    .Where(x => x.CategoryID == categoryId)
                    .OrderByDescending(x => x.DateAdded);

                PagedList<Product> model = new PagedList<Product>(lsTinDangs, page, pageSize);
                ViewBag.CurrentPage = page;
                ViewBag.Category = category;

                var categories = _context.Categories.ToList();
                ViewBag.Categories = categories;


                ViewData["DanhMuc"] = new SelectList(_context.Categories, "CategoryID", "Name");

                return View(model);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpGet]
        [Route("Product/FilterAndSort", Name = "FilterAndSort")]
        public IActionResult FilterAndSort(int? categoryId = null, int? brandId = null, int sortOption = 0, int page = 1)
        {
            try
            {
                const int pageSize = 10;

                IQueryable<Product> products = _context.Products
                    .Include(p => p.Category)
                    .Include(p => p.Brand)
                    .AsNoTracking();

                if (categoryId.HasValue && categoryId.Value > 0)
                {
                    products = products.Where(p => p.CategoryID == categoryId);
                }

                if (brandId.HasValue && brandId.Value > 0)
                {
                    products = products.Where(p => p.BrandID == brandId);
                }

                products = sortOption switch
                {
                    2 => products.OrderBy(p => p.Price),
                    3 => products.OrderByDescending(p => p.Price),
                    _ => products.OrderByDescending(p => p.DateAdded)
                };

                IPagedList<Product> model = new PagedList<Product>(products, page, pageSize);

                var resultData = model.Select(p => new
                {
                    p.ProductID,
                    p.ProductName,
                    p.Price,
                    p.ImageURL,
                    CategoryName = p.Category.CategoryName,
                    BrandName = p.Brand.BrandName
                }).ToList();

                return PartialView("_ProductListPartial", model);
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                return Json(new { status = "error", message = "Error in filtering and sorting" });
            }
        }


        // Tạo thư mục tạm 

        private string CreateTempFolder()
        {
            var tempFolder = Path.Combine(_webHostEnvironment.WebRootPath, "temp");
            if (!Directory.Exists(tempFolder))
            {
                Directory.CreateDirectory(tempFolder); // Tạo thư mục nếu chưa tồn tại
            }
            return tempFolder;
        }

        [HttpPost]
        public async Task<IActionResult> UploadImage(IFormFile imageFile)
        {
            if (imageFile == null || imageFile.Length == 0)
            {
                _notyfService.Warning("Vui lòng chọn một file hợp lệ!");
                return RedirectToAction("Index"); // Chuyển hướng về trang chính
            }

            // Lấy đường dẫn thư mục tạm
            var tempFolder = CreateTempFolder();

            // Tạo tên file duy nhất
            var uniqueFileName = $"{Guid.NewGuid()}_{imageFile.FileName}";
            var filePath = Path.Combine(tempFolder, uniqueFileName);

            // Lưu file lên thư mục tạm
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await imageFile.CopyToAsync(fileStream);
            }

            _notyfService.Success("File đã được tải lên thư mục tạm!");
            TempData["TempFilePath"] = filePath; // Lưu lại đường dẫn tạm để xử lý sau
            return RedirectToAction("Index");
        }


        // Xóa thư mục tạm
        private void DeleteTempFile(string filePath)
        {
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }
        }

        // Xử lí hình ảnh


        [HttpPost]
        public IActionResult ProcessTempImage()
        {
            var tempFilePath = TempData["TempFilePath"]?.ToString();
            if (string.IsNullOrEmpty(tempFilePath) || !System.IO.File.Exists(tempFilePath))
            {
                TempData["Error"] = "Không tìm thấy file tạm để xử lý.";
                return RedirectToAction("Index");
            }

            try
            {
                // Ví dụ: Xử lý ảnh (logic thực tế của bạn)
                var result = ProcessImage(tempFilePath);

                // Xóa file tạm sau khi xử lý xong
                DeleteTempFile(tempFilePath);

                TempData["Success"] = "Xử lý ảnh thành công!";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["Error"] = $"Lỗi trong quá trình xử lý ảnh: {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        // Ví dụ: Phương thức xử lý ảnh
        private string ProcessImage(string filePath)
        {
            // Logic xử lý ảnh, ví dụ phân tích bằng OpenCV hoặc AI
            // Ở đây chỉ trả về đường dẫn làm ví dụ
            return $"Đã xử lý file: {filePath}";
        }

        [HttpPost]
        public async Task<IActionResult> AnalyzeImage(IFormFile imageFile)
        {
            if (imageFile == null || imageFile.Length == 0)
            {
                _notyfService.Warning("Vui lòng chọn một file hợp lệ!");
                return RedirectToAction("Index");
            }

BlueSports/BlueSports/Controllers/SearchController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using BlueSports.Data;
using BlueSports.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;


namespace BlueSports.Controllers
{
    public class SearchController : Controller
    {
        private readonly ApplicationDbContext _context;
        public INotyfService _notyfService { get; }
        public SearchController(ApplicationDbContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }
        
        [HttpGet]
        public async Task<IActionResult> SearchProduct(string keyword)
        {
            IQueryable<Product> query = _context.Products.Include(p => p.Category);

            if (!string.IsNullOrEmpty(keyword))
            {
                // Nếu có keyword, thực hiện tìm kiếm sản phẩm theo từ khóa
                query = query.Where(p => p.ProductName.Contains(keyword) || p.Description.Contains(keyword));
                ViewBag.Keyword = keyword; // Truyền keyword vào ViewBag để hiển thị
            }
            else
            {
                ViewBag.Keyword = "All Products"; // Hiển thị "All Products" nếu không có từ khóa
            }
            var categories = _context.Categories.ToList();
            ViewBag.Categories = categories;

            var products = await query
                .OrderByDescending(p => p.ProductName)
                .Take(18)
                .ToListAsync();

            return View(products);
        }

    }
}

BlueSports/BlueSports/Views/Shared/_FooterPartialView.cshtml
<footer class="footer border-top footer text-muted">
    <div class="container">
        <div class="row">
            <div class="footer-col">
                <h4>company</h4>
                <ul>
                    <li><a href="#">about us</a></li>
                    <li><a href="#">our services</a></li>
                    <li><a href="#">privacy policy</a></li>
                    <li><a href="#">Warrabty policy</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>get help</h4>
                <ul>
                    <li><a href="#">shipping</a></li>
                    <li><a href="#">returns</a></li>
                    <li><a href="#">order status</a></li>
                    <li><a href="#">payment options</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>online shop</h4>
                <ul>
                    <li><a href="#">Laptop</a></li>
                    <li><a href="#">PC</a></li>
                    <li><a href="#">Screen</a></li>
                    <li><a href="#">Keyboard</a></li>
                </ul>
            </div>
            <div class="footer-col">
                <h4>follow us</h4>
                <div class="social-links">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                    <a href="#"><i class="fab fa-linkedin-in"></i></a>
                </div>
            </div>
        </div>
        <div class="copyright">
            Copyright &copy; 2022 <strong>BlueSport</strong>. Powered by UIT - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>


    </div>
</footer>

BlueSports/BlueSports/Views/Shared/_Layout.cshtml
@using AspNetCoreHero.ToastNotification
@{
    ViewData["Title"] = "Home";
}



<!DOCTYPE html>
<html lang="vi">
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>BlueSports</title>

    <link rel="shortcut icon" href="~/favicon_transparent.png">
    <link rel="stylesheet" href="~/css/Bootswatch.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="/_Layout.cshtml.css" asp-append-version="true" />
    <link rel="stylesheet" href="BlueSports.styles.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.css" />
    <script src="https://kit.fontawesome.com/3518e7db2c.js" crossorigin="anonymous"></script>


    <!-- Vendor CSS (Contain Bootstrap, Icon Fonts) -->
    <link rel="stylesheet" href="~/css/vendor/font-awesome.min.css" />
    <link rel="stylesheet" href="~/css/vendor/Pe-icon-7-stroke.css" />

    <!-- Plugin CSS (Global Plugins Files) -->
    <link rel="stylesheet" href="~/css/plugins/animate.min.css">
    <link rel="stylesheet" href="~/css/plugins/jquery-ui.min.css">
    <link rel="stylesheet" href="~/css/plugins/swiper-bundle.min.css">
    <link rel="stylesheet" href="~/css/plugins/nice-select.css">
    <link rel="stylesheet" href="~/css/plugins/magnific-popup.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom py-4 box-shadow">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/logo_transparent.png" width="50" height="80"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                            <form asp-controller="Search" asp-action="SearchProduct" class="d-flex offset-1" method="get">
        @Html.AntiForgeryToken()
        <input class="form-control search-bar" name="keyword" type="text" placeholder="Tìm kiếm">
        <button class="btn search-btn" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                </form>


                        <!-- icon camera Dropdown  -->
                        <div class="btn-group ms-2">
                            <button type="button" class="btn btn-outline-secondary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                                <i class="fa-solid fa-camera"></i>
                            </button>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="dropdownMenuButton">
                                <li>
                                    <form asp-action="AnalyzeImage" asp-controller="Product" enctype="multipart/form-data" method="post">
                                        <label class="dropdown-item">
                                            <i class="fa-solid fa-upload me-2"></i>
                                            <input type="file" name="imageFile" class="d-none" onchange="this.form.submit()" accept="image/*" /> Tải ảnh lên
                                        </label>
                                    </form>
                                </li>
                                <li>
                                    <button class="dropdown-item" onclick="openCamera()">
                                        <i class="fa-solid fa-camera-retro me-2"></i> Chụp ảnh
                                    </button>
                                </li>
                            </ul>
                        </div>

                        @*<form class="d-flex offset-1">
                        <input class="form-control search-bar" type="text" placeholder="Tìm kiếm">
                        <button class="btn search-btn" type="submit"><i class="fa-solid fa-magnifying-glass"></i></button>
                        </form>*@
                        <li class="offset-1" style="margin-top: 7px">
                            <div>
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <i class="fa-solid fa-user"></i> <a class="text-dark fw-semibold" style="text-decoration: none" href="/my-account">&nbsp;Tài khoản</a>
                                    <a class="text-dark fw-semibold" style="text-decoration: none" asp-controller="Logout" asp-action="Index">| Đăng xuất </a>
                                }
                                else
                                {
                                    <i class="fa-solid fa-user"></i> <a class="text-dark fw-semibold" style="text-decoration: none" href="/Log-in">&nbsp;Đăng Nhập </a>
                                    <a class="text-dark fw-semibold" style="text-decoration: none" asp-area="" asp-controller="Register" asp-action="Index">| Đăng Ký </a>
                                }


                            </div>
                        </li>
                        <li id="numberCart" class="offset-1 minicart-wrap me-3 me-lg-0">
                            @await Component.InvokeAsync("NumberCart")
                        </li>

                        @* <li class="offset-1">
                        <div style="margin-top: 7px">
                        <i class="fa-solid fa-cart-shopping"></i>
                        <div class="offcanvas-minicart_wrapper" id="miniCart">
                        <a class="text-dark fw-semibold" style="text-decoration: none" href="cart.html">
                        &nbsp;Cart
                        </a>
                        @await Component.InvokeAsync("HeaderCart")

                        </div>

                        </div>
                        </li> *@
                    </ul>
                </div>
            </div>
        </nav>
        <div class="offcanvas-minicart_wrapper" id="miniCart">
            @await Component.InvokeAsync("HeaderCart")
        </div>
    </header>
    <main role="main" class="">
        @RenderBody()
        <div class="sub-main">
            <a class="gotopbtn" href="#"><i class="fas fa-arrow-up"> </i></a>
        </div>
    </main>
    <footer class="footer border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class="footer-col">
                    <h4>company</h4>
                    <ul>
                        <li><a href="#">about us</a></li>
                        <li><a href="#">our services</a></li>
                        <li><a href="#">privacy policy</a></li>
                        <li><a href="#">Warrabty policy</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>get help</h4>
                    <ul>
                        <li><a href="#">shipping</a></li>
                        <li><a href="#">returns</a></li>
                        <li><a href="#">order status</a></li>
                        <li><a href="#">payment options</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>online shop</h4>
                    <ul>
                        <li><a href="/danhmuc/laptop">Laptop</a></li>
                        <li><a href="#">PC</a></li>
                        <li><a href="#">Screen</a></li>
                        <li><a href="#">Keyboard</a></li>
                    </ul>
                </div>
                <div class="footer-col">
                    <h4>follow us</h4>
                    <div class="social-links">
                        <a href="#"><i class="fab fa-facebook-f"></i></a>
                        <a href="#"><i class="fab fa-twitter"></i></a>
                        <a href="#"><i class="fab fa-instagram"></i></a>
                        <a href="#"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="copyright">
            Copyright &copy; 2024 <strong>BlueSports</strong>. Powered by UIT - <a asp-area="" asp-controller="Home" asp-action="Privacy" style="text-decoration:none">Our Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/swiper/swiper-bundle.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.js" integrity="sha256-3zlB5s2uwoUzrXK3BT7AX3FyvojsraNFxCc2vC/7pNI=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <!-- Vendor JS -->
    <script src="~/js/vendor/bootstrap.bundle.min.js"></script>
    <script src="~/js/vendor/jquery-3.5.1.min.js"></script>
    <script src="~/js/vendor/jquery-migrate-3.3.0.min.js"></script>
    <script src="~/js/vendor/modernizr-3.11.2.min.js"></script>
    <script src="~/js/vendor/jquery.waypoints.js"></script>

    <!--Plugins JS-->
    <script src="~/js/plugins/wow.min.js"></script>
    <script src="~/js/plugins/jquery-ui.min.js"></script>
    <script src="~/js/plugins/swiper-bundle.min.js"></script>
    <script src="~/js/plugins/jquery.nice-select.js"></script>
    <script src="~/js/plugins/parallax.min.js"></script>
    <script src="~/js/plugins/jquery.magnific-popup.min.js"></script>

    <!--Main JS (Common Activation Codes)-->
    <script src="~/js/main.js"></script>

    @await Component.InvokeAsync("Notyf")
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("Styles", required: false)
</body>
</html>

BlueSports/BlueSports/Views/Shared/_LayoutAccount.cshtml
<!DOCTYPE html>

<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/favicon_transparent.png">
    <!-- CSS -->
    <link rel="stylesheet" href="~/css/style_login.css" asp-append-version="true" />
    <title>@ViewData["Title"]</title>
    <!-- Boxicons CSS -->
    <link href='https://unpkg.com/boxicons@2.1.2/css/boxicons.min.css' rel='stylesheet'>
</head>
<body style="margin-bottom: 0">
    <div class="container-login forms">
        @RenderBody()
    </div>
    <script src="~/js/script_login.js"></script>
    @await Component.InvokeAsync("Notyf")
</body>
</html>